# Generated by Django 4.2.4 on 2023-08-08 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_subscription_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 11, 32, 52, 763271, tzinfo=datetime.timezone.utc)),
        ),
    ]
